// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

#ifndef PROTOBUF_heartbeat_2eproto__INCLUDED
#define PROTOBUF_heartbeat_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace protoc {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_heartbeat_2eproto();
void protobuf_AssignDesc_heartbeat_2eproto();
void protobuf_ShutdownFile_heartbeat_2eproto();

class Heartbeat;
class HeartbeatAck;

// ===================================================================

class Heartbeat : public ::google::protobuf::Message {
 public:
  Heartbeat();
  virtual ~Heartbeat();
  
  Heartbeat(const Heartbeat& from);
  
  inline Heartbeat& operator=(const Heartbeat& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Heartbeat& default_instance();
  
  void Swap(Heartbeat* other);
  
  // implements Message ----------------------------------------------
  
  Heartbeat* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Heartbeat& from);
  void MergeFrom(const Heartbeat& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string session = 1;
  inline bool has_session() const;
  inline void clear_session();
  static const int kSessionFieldNumber = 1;
  inline const ::std::string& session() const;
  inline void set_session(const ::std::string& value);
  inline void set_session(const char* value);
  inline void set_session(const char* value, size_t size);
  inline ::std::string* mutable_session();
  inline ::std::string* release_session();
  
  // @@protoc_insertion_point(class_scope:protoc.Heartbeat)
 private:
  inline void set_has_session();
  inline void clear_has_session();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* session_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_heartbeat_2eproto();
  friend void protobuf_AssignDesc_heartbeat_2eproto();
  friend void protobuf_ShutdownFile_heartbeat_2eproto();
  
  void InitAsDefaultInstance();
  static Heartbeat* default_instance_;
};
// -------------------------------------------------------------------

class HeartbeatAck : public ::google::protobuf::Message {
 public:
  HeartbeatAck();
  virtual ~HeartbeatAck();
  
  HeartbeatAck(const HeartbeatAck& from);
  
  inline HeartbeatAck& operator=(const HeartbeatAck& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const HeartbeatAck& default_instance();
  
  void Swap(HeartbeatAck* other);
  
  // implements Message ----------------------------------------------
  
  HeartbeatAck* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeartbeatAck& from);
  void MergeFrom(const HeartbeatAck& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string server_time = 1;
  inline bool has_server_time() const;
  inline void clear_server_time();
  static const int kServerTimeFieldNumber = 1;
  inline const ::std::string& server_time() const;
  inline void set_server_time(const ::std::string& value);
  inline void set_server_time(const char* value);
  inline void set_server_time(const char* value, size_t size);
  inline ::std::string* mutable_server_time();
  inline ::std::string* release_server_time();
  
  // @@protoc_insertion_point(class_scope:protoc.HeartbeatAck)
 private:
  inline void set_has_server_time();
  inline void clear_has_server_time();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* server_time_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_heartbeat_2eproto();
  friend void protobuf_AssignDesc_heartbeat_2eproto();
  friend void protobuf_ShutdownFile_heartbeat_2eproto();
  
  void InitAsDefaultInstance();
  static HeartbeatAck* default_instance_;
};
// ===================================================================


// ===================================================================

// Heartbeat

// required string session = 1;
inline bool Heartbeat::has_session() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Heartbeat::set_has_session() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Heartbeat::clear_has_session() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Heartbeat::clear_session() {
  if (session_ != &::google::protobuf::internal::kEmptyString) {
    session_->clear();
  }
  clear_has_session();
}
inline const ::std::string& Heartbeat::session() const {
  return *session_;
}
inline void Heartbeat::set_session(const ::std::string& value) {
  set_has_session();
  if (session_ == &::google::protobuf::internal::kEmptyString) {
    session_ = new ::std::string;
  }
  session_->assign(value);
}
inline void Heartbeat::set_session(const char* value) {
  set_has_session();
  if (session_ == &::google::protobuf::internal::kEmptyString) {
    session_ = new ::std::string;
  }
  session_->assign(value);
}
inline void Heartbeat::set_session(const char* value, size_t size) {
  set_has_session();
  if (session_ == &::google::protobuf::internal::kEmptyString) {
    session_ = new ::std::string;
  }
  session_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Heartbeat::mutable_session() {
  set_has_session();
  if (session_ == &::google::protobuf::internal::kEmptyString) {
    session_ = new ::std::string;
  }
  return session_;
}
inline ::std::string* Heartbeat::release_session() {
  clear_has_session();
  if (session_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = session_;
    session_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// HeartbeatAck

// required string server_time = 1;
inline bool HeartbeatAck::has_server_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeartbeatAck::set_has_server_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeartbeatAck::clear_has_server_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeartbeatAck::clear_server_time() {
  if (server_time_ != &::google::protobuf::internal::kEmptyString) {
    server_time_->clear();
  }
  clear_has_server_time();
}
inline const ::std::string& HeartbeatAck::server_time() const {
  return *server_time_;
}
inline void HeartbeatAck::set_server_time(const ::std::string& value) {
  set_has_server_time();
  if (server_time_ == &::google::protobuf::internal::kEmptyString) {
    server_time_ = new ::std::string;
  }
  server_time_->assign(value);
}
inline void HeartbeatAck::set_server_time(const char* value) {
  set_has_server_time();
  if (server_time_ == &::google::protobuf::internal::kEmptyString) {
    server_time_ = new ::std::string;
  }
  server_time_->assign(value);
}
inline void HeartbeatAck::set_server_time(const char* value, size_t size) {
  set_has_server_time();
  if (server_time_ == &::google::protobuf::internal::kEmptyString) {
    server_time_ = new ::std::string;
  }
  server_time_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* HeartbeatAck::mutable_server_time() {
  set_has_server_time();
  if (server_time_ == &::google::protobuf::internal::kEmptyString) {
    server_time_ = new ::std::string;
  }
  return server_time_;
}
inline ::std::string* HeartbeatAck::release_server_time() {
  clear_has_server_time();
  if (server_time_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = server_time_;
    server_time_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protoc

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_heartbeat_2eproto__INCLUDED
