//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: quote.proto
namespace entity
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Quote")]
  public partial class Quote : global::ProtoBuf.IExtensible
  {
    public Quote() {}
    
    private string _symbol;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"symbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbol
    {
      get { return _symbol; }
      set { _symbol = value; }
    }
    private string _trading_day;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"trading_day", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string trading_day
    {
      get { return _trading_day; }
      set { _trading_day = value; }
    }
    private string _exchange_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"exchange_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string exchange_id
    {
      get { return _exchange_id; }
      set { _exchange_id = value; }
    }
    private string _exchange_symbol_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"exchange_symbol_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string exchange_symbol_id
    {
      get { return _exchange_symbol_id; }
      set { _exchange_symbol_id = value; }
    }
    private double _last;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"last", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double last
    {
      get { return _last; }
      set { _last = value; }
    }
    private double _prev_settlement_price;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"prev_settlement_price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double prev_settlement_price
    {
      get { return _prev_settlement_price; }
      set { _prev_settlement_price = value; }
    }
    private double _prev_close;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"prev_close", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double prev_close
    {
      get { return _prev_close; }
      set { _prev_close = value; }
    }
    private double _prev_open_interest;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"prev_open_interest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double prev_open_interest
    {
      get { return _prev_open_interest; }
      set { _prev_open_interest = value; }
    }
    private double _open;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"open", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double open
    {
      get { return _open; }
      set { _open = value; }
    }
    private double _high;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double high
    {
      get { return _high; }
      set { _high = value; }
    }
    private double _low;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double low
    {
      get { return _low; }
      set { _low = value; }
    }
    private int _volume;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"volume", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int volume
    {
      get { return _volume; }
      set { _volume = value; }
    }
    private double _turnover;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"turnover", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double turnover
    {
      get { return _turnover; }
      set { _turnover = value; }
    }
    private double _open_interest;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"open_interest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double open_interest
    {
      get { return _open_interest; }
      set { _open_interest = value; }
    }
    private double _close;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"close", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double close
    {
      get { return _close; }
      set { _close = value; }
    }
    private double _settlement_price;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"settlement_price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double settlement_price
    {
      get { return _settlement_price; }
      set { _settlement_price = value; }
    }
    private double _upper_limit_price;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"upper_limit_price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double upper_limit_price
    {
      get { return _upper_limit_price; }
      set { _upper_limit_price = value; }
    }
    private double _lower_limit_price;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"lower_limit_price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double lower_limit_price
    {
      get { return _lower_limit_price; }
      set { _lower_limit_price = value; }
    }
    private double _prev_delta;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"prev_delta", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double prev_delta
    {
      get { return _prev_delta; }
      set { _prev_delta = value; }
    }
    private double _curr_delta;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"curr_delta", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double curr_delta
    {
      get { return _curr_delta; }
      set { _curr_delta = value; }
    }
    private string _update_time;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"update_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string update_time
    {
      get { return _update_time; }
      set { _update_time = value; }
    }
    private int _update_millisec;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"update_millisec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int update_millisec
    {
      get { return _update_millisec; }
      set { _update_millisec = value; }
    }
    private double _bid;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double bid
    {
      get { return _bid; }
      set { _bid = value; }
    }
    private int _bid_size;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"bid_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bid_size
    {
      get { return _bid_size; }
      set { _bid_size = value; }
    }
    private double _ask;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"ask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double ask
    {
      get { return _ask; }
      set { _ask = value; }
    }
    private int _ask_size;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"ask_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ask_size
    {
      get { return _ask_size; }
      set { _ask_size = value; }
    }
    private double _bid_2;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"bid_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double bid_2
    {
      get { return _bid_2; }
      set { _bid_2 = value; }
    }
    private int _bid_size_2;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"bid_size_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bid_size_2
    {
      get { return _bid_size_2; }
      set { _bid_size_2 = value; }
    }
    private double _ask_2;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"ask_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double ask_2
    {
      get { return _ask_2; }
      set { _ask_2 = value; }
    }
    private int _ask_size_2;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"ask_size_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ask_size_2
    {
      get { return _ask_size_2; }
      set { _ask_size_2 = value; }
    }
    private double _bid_3;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"bid_3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double bid_3
    {
      get { return _bid_3; }
      set { _bid_3 = value; }
    }
    private int _bid_size_3;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"bid_size_3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bid_size_3
    {
      get { return _bid_size_3; }
      set { _bid_size_3 = value; }
    }
    private double _ask_3;
    [global::ProtoBuf.ProtoMember(33, IsRequired = true, Name=@"ask_3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double ask_3
    {
      get { return _ask_3; }
      set { _ask_3 = value; }
    }
    private int _ask_size_3;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"ask_size_3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ask_size_3
    {
      get { return _ask_size_3; }
      set { _ask_size_3 = value; }
    }
    private double _bid_4;
    [global::ProtoBuf.ProtoMember(35, IsRequired = true, Name=@"bid_4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double bid_4
    {
      get { return _bid_4; }
      set { _bid_4 = value; }
    }
    private int _bid_size_4;
    [global::ProtoBuf.ProtoMember(36, IsRequired = true, Name=@"bid_size_4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bid_size_4
    {
      get { return _bid_size_4; }
      set { _bid_size_4 = value; }
    }
    private double _ask_4;
    [global::ProtoBuf.ProtoMember(37, IsRequired = true, Name=@"ask_4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double ask_4
    {
      get { return _ask_4; }
      set { _ask_4 = value; }
    }
    private int _ask_size_4;
    [global::ProtoBuf.ProtoMember(38, IsRequired = true, Name=@"ask_size_4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ask_size_4
    {
      get { return _ask_size_4; }
      set { _ask_size_4 = value; }
    }
    private double _bid_5;
    [global::ProtoBuf.ProtoMember(39, IsRequired = true, Name=@"bid_5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double bid_5
    {
      get { return _bid_5; }
      set { _bid_5 = value; }
    }
    private int _bid_size_5;
    [global::ProtoBuf.ProtoMember(40, IsRequired = true, Name=@"bid_size_5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bid_size_5
    {
      get { return _bid_size_5; }
      set { _bid_size_5 = value; }
    }
    private double _ask_5;
    [global::ProtoBuf.ProtoMember(41, IsRequired = true, Name=@"ask_5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double ask_5
    {
      get { return _ask_5; }
      set { _ask_5 = value; }
    }
    private int _ask_size_5;
    [global::ProtoBuf.ProtoMember(42, IsRequired = true, Name=@"ask_size_5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ask_size_5
    {
      get { return _ask_size_5; }
      set { _ask_size_5 = value; }
    }
    private double _average_price;
    [global::ProtoBuf.ProtoMember(43, IsRequired = true, Name=@"average_price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double average_price
    {
      get { return _average_price; }
      set { _average_price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}